### ISSUE TITLE
Add padding-top to the textarea

### ISSUE THREAD

**Issue by danutibe07** [Santosh-Konappanavar/PortFolio#8]
![issue](https://user-images.githubusercontent.com/54628727/215692953-1da7b5ad-e99f-4a3b-ae68-c203337907ae.png)

**Comment by ab-noori** [comment]
### Highlights 👍 
- Nice design
- Best practices flowed
- Good responsiveness
### Suggested changes ♻️ 
- It would be better to solve the problem of two scrollbar
- it would be better to be careful of font sizes

**Comment by bilalrajput09** [comment]
**Suggested changes**

Good job so far !! 
I think it will be better to have less margin-bottom for cards so it in that way it will be more identical to figma design,
![Screenshot 2023-01-31 083653](https://user-images.githubusercontent.com/116716918/215696456-4221f270-f3da-4932-ad5c-625fafe3d466.png)
